import { Howl } from 'howler';
import './style.css';

const $ = (id) => document.getElementById(id);
const app = $('app');

app.innerHTML = `
  <main class="min-h-dvh w-full overflow-hidden bg-gradient-to-br from-stone-100 via-teal-50 to-amber-50 text-slate-800 selection:bg-teal-200 pb-[74px]">
    <section class="mx-auto flex min-h-dvh w-full max-w-md flex-col px-4 pb-[72px] pt-3 sm:max-w-lg">
      <header class="flex items-center justify-between gap-3 rounded-3xl border border-white/80 bg-white/70 p-3 shadow-xl shadow-teal-900/5 backdrop-blur">
        <div><h1 class="font-display text-xl tracking-wide text-teal-900">Restore & Sell</h1><p class="text-xs font-medium text-slate-500">Kutu seç • Restore et • Pazarlık yap</p></div>
        <div class="flex items-center gap-2 rounded-2xl bg-slate-900 px-3 py-2 text-right text-white shadow-inner"><span class="text-lg">💵</span><div><p id="money" class="font-display text-lg leading-4">$0</p><p id="best" class="text-[10px] uppercase tracking-wider text-teal-200">Rekor $0</p></div></div>
      </header>

      <div class="mt-3 grid grid-cols-3 gap-2 text-center">
        <div class="rounded-2xl bg-white/75 p-2 shadow-sm ring-1 ring-white/80"><p class="text-[10px] font-bold uppercase tracking-wider text-slate-400">Ürün</p><p id="objectName" class="truncate font-bold text-teal-900">Kutu bekliyor</p></div>
        <div class="rounded-2xl bg-white/75 p-2 shadow-sm ring-1 ring-white/80"><p class="text-[10px] font-bold uppercase tracking-wider text-slate-400">Durum</p><p id="condition" class="font-bold text-teal-900">0%</p></div>
        <div class="rounded-2xl bg-white/75 p-2 shadow-sm ring-1 ring-white/80"><p class="text-[10px] font-bold uppercase tracking-wider text-slate-400">Teklif</p><p id="value" class="font-bold text-teal-900">$0</p></div>
      </div>

      <section class="relative mt-4 flex flex-1 min-h-[350px] items-center justify-center rounded-[2rem] border border-white/80 bg-white/60 p-3 shadow-2xl shadow-teal-950/10 backdrop-blur">
        <div class="absolute left-5 top-5 z-10 rounded-full bg-teal-900/90 px-3 py-1 text-xs font-bold text-white shadow-lg" id="hint">Başlamak için tıkla</div>
        <canvas id="restoreCanvas" class="touch-none rounded-[1.5rem] bg-gradient-to-b from-slate-50 to-stone-100 shadow-inner ring-1 ring-slate-200"></canvas>
        <div id="startOverlay" class="absolute inset-0 z-30 flex flex-col items-center justify-center rounded-[2rem] bg-white/85 p-8 text-center backdrop-blur-md">
          <div class="mb-4 text-6xl drop-shadow">📦✨</div><h2 class="font-display text-4xl leading-tight text-teal-950">Restore & Sell</h2>
          <p class="mt-3 max-w-xs text-sm font-medium text-slate-600">Önce 3 gizemli kutudan birini seç. Sonra çıkan eşyayı temizle, antikacıyla pazarlık yap veya rafa bırak.</p>
          <button id="startBtn" class="mt-6 rounded-2xl bg-teal-600 px-8 py-4 font-display text-lg text-white shadow-xl shadow-teal-700/25 active:scale-95">Kutu Seç</button>
        </div>
        <div id="completeOverlay" class="pointer-events-none absolute inset-0 z-20 hidden flex-col items-center justify-center rounded-[2rem] bg-amber-50/35 text-center backdrop-blur-[1px]"><div class="animate-pop text-7xl">🤝</div><p class="font-display text-4xl text-amber-600 drop-shadow-sm">ANLAŞMA!</p><p id="earnedText" class="mt-1 rounded-full bg-white/90 px-4 py-2 font-display text-2xl text-teal-800 shadow-lg">+$0</p></div>
      </section>

      <section class="mt-3 grid grid-cols-5 gap-2" id="toolBar">
        <button data-tool="scrape" class="tool-btn rounded-2xl bg-white/85 p-2 text-center shadow ring-1 ring-white active:scale-95"><p class="text-xl">🪥</p><p class="text-[10px] font-bold">Kazı</p></button>
        <button data-tool="wash" class="tool-btn rounded-2xl bg-white/85 p-2 text-center shadow ring-1 ring-white active:scale-95"><p class="text-xl">🧼</p><p class="text-[10px] font-bold">Köpük</p></button>
        <button data-tool="rinse" class="tool-btn rounded-2xl bg-white/85 p-2 text-center shadow ring-1 ring-white active:scale-95"><p class="text-xl">💧</p><p class="text-[10px] font-bold">Durula</p></button>
        <button data-tool="repair" class="tool-btn rounded-2xl bg-white/85 p-2 text-center shadow ring-1 ring-white active:scale-95"><p class="text-xl">🔧</p><p class="text-[10px] font-bold">Onar</p></button>
        <button data-tool="polish" class="tool-btn rounded-2xl bg-white/85 p-2 text-center shadow ring-1 ring-white active:scale-95"><p class="text-xl">✨</p><p class="text-[10px] font-bold">Cilala</p></button>
      </section>

      <div class="mt-2 grid grid-cols-4 gap-2 text-[10px] font-bold text-slate-600">
        <p id="mClean" class="rounded-xl bg-white/70 px-2 py-1">Kir 0%</p><p id="mFoam" class="rounded-xl bg-white/70 px-2 py-1">Köpük 0%</p><p id="mRepair" class="rounded-xl bg-white/70 px-2 py-1">Sağlam 0%</p><p id="mPolish" class="rounded-xl bg-white/70 px-2 py-1">Cila 0%</p>
      </div>

      <section class="mt-3 grid grid-cols-3 gap-3">
        <button id="sellBtn" class="rounded-3xl bg-amber-400 p-3 text-left shadow-lg shadow-amber-700/10 ring-1 ring-white transition active:scale-[0.98]"><p class="font-display text-sm text-amber-950">🏬 Pazara Git</p><p class="text-xs text-amber-800">Antikacıyla görüş</p><p id="sellQuote" class="mt-2 font-bold text-amber-950">$0</p></button>
        <button id="speedBtn" class="rounded-3xl bg-white/85 p-3 text-left shadow-lg shadow-slate-900/5 ring-1 ring-white transition active:scale-[0.98] disabled:opacity-45"><p class="font-display text-sm text-teal-900">⚡ Hız</p><p class="text-xs text-slate-500">Alet alanı büyür</p><p id="speedCost" class="mt-2 font-bold text-amber-600">$60</p></button>
        <button id="unlockBtn" class="rounded-3xl bg-white/85 p-3 text-left shadow-lg shadow-slate-900/5 ring-1 ring-white transition active:scale-[0.98] disabled:opacity-45"><p class="font-display text-sm text-teal-900">📦 Pazar</p><p class="text-xs text-slate-500">Daha iyi kutular</p><p id="unlockCost" class="mt-2 font-bold text-amber-600">$140</p></button>
      </section>
    </section>
  </main>

  <div id="boxOverlay" class="fixed inset-0 z-40 hidden items-center justify-center bg-slate-950/45 p-4 backdrop-blur-sm">
    <div class="w-full max-w-md rounded-[2rem] bg-white p-5 text-center shadow-2xl"><h2 class="font-display text-2xl text-teal-950">3 Kutudan Birini Seç</h2><p class="mt-1 text-sm font-medium text-slate-500">Seçimden sonra kaçırdıklarını da göreceksin.</p><div id="boxGrid" class="mt-5 grid grid-cols-3 gap-3"></div><button id="boxContinue" class="mt-5 hidden w-full rounded-2xl bg-teal-600 px-6 py-3 font-display text-white active:scale-95">Seçtiğim Ürünü Temizle</button></div>
  </div>

  <div id="marketOverlay" class="fixed inset-0 z-40 hidden items-center justify-center bg-slate-950/45 p-4 backdrop-blur-sm">
    <div class="w-full max-w-md rounded-[2rem] bg-gradient-to-b from-amber-50 to-white p-4 shadow-2xl">
      <div class="flex items-start gap-3"><div class="rounded-2xl bg-amber-200 p-3 text-4xl">🧔</div><div class="flex-1"><h2 class="font-display text-xl text-amber-950">Antikacı Kemal</h2><p id="dealerLine" class="text-sm font-semibold text-slate-600">Bakalım bu parça ne eder...</p></div></div>
      <div class="mt-4 rounded-2xl bg-white/80 p-3 ring-1 ring-amber-100"><p id="marketItem" class="font-bold text-teal-900">Ürün</p><p id="marketStats" class="text-xs text-slate-500">Durum</p><p id="marketOffer" class="mt-2 font-display text-3xl text-amber-600">$0</p></div>
      <div class="mt-3 grid grid-cols-3 gap-2"><button id="haggleBtn" class="rounded-2xl bg-teal-600 p-3 text-xs font-display text-white active:scale-95">Pazarlık</button><button id="acceptBtn" class="rounded-2xl bg-amber-400 p-3 text-xs font-display text-amber-950 active:scale-95">Sat</button><button id="shelfBtn" class="rounded-2xl bg-slate-800 p-3 text-xs font-display text-white active:scale-95">Rafa Bırak</button></div>
      <div class="mt-4 rounded-2xl bg-slate-900 p-3 text-white"><div class="flex items-center justify-between"><p class="font-display text-sm">Dükkan Rafı</p><p class="text-[10px] text-slate-300">Bazıları hemen satılmaz</p></div><div id="shelfList" class="mt-2 grid min-h-[62px] grid-cols-3 gap-2"></div></div>
    </div>
  </div>

  <div id="ad-container" aria-label="Reklam alanı" class="fixed bottom-2 left-1/2 z-50 flex h-[50px] w-[320px] -translate-x-1/2 items-center justify-center rounded-xl border border-dashed border-slate-300 bg-white/80 text-[11px] font-bold uppercase tracking-[0.25em] text-slate-400 shadow-lg backdrop-blur">320x50 Ad Banner</div>
`;

const canvas = $('restoreCanvas'), ctx = canvas.getContext('2d');
const dirtCanvas = document.createElement('canvas'), dirtCtx = dirtCanvas.getContext('2d');
const foamCanvas = document.createElement('canvas'), foamCtx = foamCanvas.getContext('2d');
const ui = { money: $('money'), best: $('best'), objectName: $('objectName'), condition: $('condition'), value: $('value'), hint: $('hint'), startOverlay: $('startOverlay'), completeOverlay: $('completeOverlay'), earnedText: $('earnedText'), speedBtn: $('speedBtn'), unlockBtn: $('unlockBtn'), speedCost: $('speedCost'), unlockCost: $('unlockCost'), startBtn: $('startBtn'), sellBtn: $('sellBtn'), sellQuote: $('sellQuote'), mClean: $('mClean'), mFoam: $('mFoam'), mRepair: $('mRepair'), mPolish: $('mPolish'), boxOverlay: $('boxOverlay'), boxGrid: $('boxGrid'), boxContinue: $('boxContinue'), marketOverlay: $('marketOverlay'), dealerLine: $('dealerLine'), marketItem: $('marketItem'), marketStats: $('marketStats'), marketOffer: $('marketOffer'), haggleBtn: $('haggleBtn'), acceptBtn: $('acceptBtn'), shelfBtn: $('shelfBtn'), shelfList: $('shelfList') };

const types = ['Osmanlı Vazosu', 'Cep Saati', 'Bakır Demlik', 'Gümüş Kadeh', 'Retro Radyo', 'Oyuncak Robot', 'Antika Kamera', 'Müzik Kutusu', 'Minyatür Sandık', 'Porselen Tabak', 'Pirinç Pusula', 'Ahşap Heykel'];
const icons = ['🏺','🕰️','🫖','🏆','📻','🤖','📷','🎼','🧰','🍽️','🧭','🗿'];
const materials = ['Bakır', 'Porselen', 'Gümüş', 'Bronz', 'Ahşap', 'Kristal', 'Pirinç', 'Emaye'];
const dirtNames = ['çamurlu', 'paslı', 'isli', 'tozlu', 'yağlı', 'yosunlu', 'kararmış', 'lekeli'];
const palettes = [['#0f766e','#5eead4','#f59e0b'], ['#7c2d12','#fbbf24','#451a03'], ['#b45309','#fed7aa','#78350f'], ['#4338ca','#c4b5fd','#facc15'], ['#334155','#94a3b8','#14b8a6'], ['#7e22ce','#f0abfc','#facc15'], ['#155e75','#67e8f9','#fb7185'], ['#166534','#86efac','#fde047']];
let state = JSON.parse(localStorage.getItem('restore-sell-save-v3') || '{}');
let money = Number(state.money || 0), best = Number(state.best || 0), brushLevel = Number(state.brushLevel || 1), marketLevel = Number(state.marketLevel || 1), nextSeed = Number(state.nextSeed || 1001), shelf = Array.isArray(state.shelf) ? state.shelf : [];
let item, boxChoices = [], picked = -1, tool = 'scrape', dragging = false, started = false, selling = false, cleanRatio = 0, foamRatio = 0, repairRatio = 0, polishRatio = 0, lastSample = 0, particles = [], floating = [], offer = 0, haggles = 0;
let audioReady = false, clickSfx, sellSfx, upgradeSfx;

function rnd(seed) { return () => ((seed = (seed * 1664525 + 1013904223) >>> 0) / 4294967296); }
function makeItem(seed) { const r = rnd(seed), typeId = Math.floor(r() * types.length), matId = Math.floor(r() * materials.length), dirtId = Math.floor(r() * dirtNames.length), rare = 1 + Math.floor(r() * Math.min(7, marketLevel + 2)); const base = Math.floor((75 + typeId * 18 + matId * 15 + rare * 48) * (1 + marketLevel * .1)); const needs = ['scrape']; if (r() > .25) needs.push('wash'); if (r() > .38) needs.push('polish'); if (r() > .45) needs.push('repair'); return { seed, typeId, matId, dirtId, rare, base, needs, icon: icons[typeId], name: `${materials[matId]} ${types[typeId]} #${seed.toString(36).toUpperCase()}`, palette: palettes[(typeId + matId) % palettes.length], grime: .68 + r() * .55, damage: needs.includes('repair') ? .35 + r() * .55 : .12 + r() * .18, shape: typeId % 6 }; }
function initAudio(){ if(audioReady) return; audioReady = true; clickSfx = new Howl({src:['/audio/ui-click.wav'], volume:.35}); sellSfx = new Howl({src:['/audio/impact-bell-heavy.ogg'], volume:.55}); upgradeSfx = new Howl({src:['/audio/ui-switch.wav'], volume:.35}); }
function save(){ localStorage.setItem('restore-sell-save-v3', JSON.stringify({ money, best, brushLevel, marketLevel, nextSeed, shelf })); }
function brushRadius(){ return (24 + brushLevel * 7) * (canvas.width / 400); }
function speedCost(){ return Math.floor(70 * Math.pow(1.68, brushLevel - 1)); }
function marketCost(){ return Math.floor(150 * Math.pow(1.85, marketLevel - 1)); }
function fitCanvas(){ const wrap = canvas.parentElement.getBoundingClientRect(); const size = Math.floor(Math.min(wrap.width - 24, wrap.height - 24, 430)); const dpr = Math.min(window.devicePixelRatio || 1, 2); canvas.style.width = `${size}px`; canvas.style.height = `${size}px`; canvas.width = dirtCanvas.width = foamCanvas.width = Math.floor(size * dpr); canvas.height = dirtCanvas.height = foamCanvas.height = Math.floor(size * dpr); if(item) resetLayers(); else { item = makeItem(nextSeed); resetLayers(); item = null; } }

function drawSilhouette(c, fillOnly = false) { if(!item) return; const w = canvas.width, h = canvas.height, s = w / 400, cx = w / 2, cy = h * .54, [dark, light, accent] = item.palette; c.save(); c.translate(cx, cy); c.scale(s, s); c.lineCap = c.lineJoin = 'round'; c.shadowColor = 'rgba(15,23,42,.18)'; c.shadowBlur = fillOnly ? 0 : 18; c.shadowOffsetY = fillOnly ? 0 : 16; const g = c.createLinearGradient(-120, -145, 120, 145); g.addColorStop(0, light); g.addColorStop(.48, dark); g.addColorStop(1, accent); c.fillStyle = g; if (item.shape === 0) { c.beginPath(); c.moveTo(-42,-145); c.quadraticCurveTo(-30,-95,-80,-45); c.bezierCurveTo(-130,20,-88,135,0,142); c.bezierCurveTo(88,135,130,20,80,-45); c.quadraticCurveTo(30,-95,42,-145); c.closePath(); c.fill(); c.fillRect(-50,-157,100,20); } if (item.shape === 1) { c.beginPath(); c.roundRect(-112,-104,224,208,32); c.fill(); c.fillStyle = '#fff7ed'; c.beginPath(); c.arc(0,-5,76,0,Math.PI*2); c.fill(); c.strokeStyle = dark; c.lineWidth = 10; c.stroke(); c.strokeStyle = '#111827'; c.lineWidth = 7; c.beginPath(); c.moveTo(0,-5); c.lineTo(0,-55); c.moveTo(0,-5); c.lineTo(44,18); c.stroke(); } if (item.shape === 2) { c.beginPath(); c.ellipse(0,24,108,88,0,0,Math.PI*2); c.fill(); c.strokeStyle = accent; c.lineWidth = 16; c.beginPath(); c.arc(0,-8,74,Math.PI*1.06,Math.PI*1.94); c.stroke(); c.fillStyle = accent; c.beginPath(); c.roundRect(-50,-112,100,42,18); c.fill(); c.strokeStyle = dark; c.beginPath(); c.moveTo(88,-5); c.quadraticCurveTo(160,-55,166,26); c.stroke(); } if (item.shape === 3) { c.beginPath(); c.moveTo(-78,-120); c.lineTo(78,-120); c.lineTo(43,42); c.lineTo(-43,42); c.closePath(); c.fill(); c.fillStyle = light; c.fillRect(-13,52,26,86); c.beginPath(); c.ellipse(0,143,78,18,0,0,Math.PI*2); c.fill(); } if (item.shape === 4) { c.beginPath(); c.roundRect(-124,-82,248,164,28); c.fill(); c.fillStyle = '#e2e8f0'; c.beginPath(); c.roundRect(-82,-42,108,78,14); c.fill(); c.fillStyle = accent; for(let i=0;i<3;i++){ c.beginPath(); c.arc(68+i*22,-10+i*18,12,0,Math.PI*2); c.fill(); } } if (item.shape === 5) { c.beginPath(); c.roundRect(-74,-116,148,210,40); c.fill(); c.fillStyle = light; c.beginPath(); c.arc(0,-38,36,0,Math.PI*2); c.fill(); c.fillStyle = accent; c.fillRect(-14,0,28,76); c.fillRect(-62,20,124,22); } if (!fillOnly) { c.shadowBlur = 0; c.globalCompositeOperation = 'screen'; c.fillStyle = 'rgba(255,255,255,.18)'; c.beginPath(); c.ellipse(-34,-12,24,118,.22,0,Math.PI*2); c.fill(); c.globalCompositeOperation = 'source-over'; c.strokeStyle = '#fff7'; c.lineWidth = 5; c.stroke(); } c.restore(); }
function drawDamage(c) { if(!item) return; const r = rnd(item.seed + 77), w = canvas.width, h = canvas.height; c.save(); c.strokeStyle = `rgba(30,41,59,${.65 * (1 - repairRatio)})`; c.lineWidth = 3 * w / 400; for (let i=0;i<8*item.damage;i++){ let x = w*(.32+r()*.36), y = h*(.29+r()*.48); c.beginPath(); c.moveTo(x,y); for(let j=0;j<3;j++){ x += (r()-.5)*40*w/400; y += (r()-.5)*35*w/400; c.lineTo(x,y); } c.stroke(); } c.restore(); }
function resetLayers(){ if(!item) return; cleanRatio = foamRatio = polishRatio = 0; repairRatio = Math.max(0, 1 - item.damage); selling = false; ui.completeOverlay.classList.add('hidden'); ui.completeOverlay.classList.remove('flex'); dirtCtx.clearRect(0,0,dirtCanvas.width,dirtCanvas.height); foamCtx.clearRect(0,0,foamCanvas.width,foamCanvas.height); drawSilhouette(dirtCtx, true); dirtCtx.globalCompositeOperation = 'source-atop'; const w=dirtCanvas.width,h=dirtCanvas.height, pat=dirtCtx.createRadialGradient(w*.45,h*.35,10,w*.5,h*.5,w*.58); const dirty = item.dirtId % 3; pat.addColorStop(0, dirty===0?'rgba(120,73,29,.55)':dirty===1?'rgba(93,64,55,.65)':'rgba(40,40,45,.58)'); pat.addColorStop(1, dirty===0?'rgba(28,25,23,.94)':dirty===1?'rgba(127,29,29,.92)':'rgba(15,23,42,.88)'); dirtCtx.fillStyle=pat; dirtCtx.fillRect(0,0,w,h); dirtCtx.globalCompositeOperation='source-over'; const r=rnd(item.seed+13); for(let i=0;i<900*item.grime;i++){ dirtCtx.fillStyle = ['rgba(41,37,36,.55)','rgba(146,64,14,.48)','rgba(15,23,42,.45)'][item.dirtId%3]; dirtCtx.beginPath(); dirtCtx.arc(r()*w,r()*h,(r()*2.8+.7)*w/400,0,Math.PI*2); dirtCtx.fill(); } updateUi(); }
function generateBoxes(){ boxChoices = [0,1,2].map(i => makeItem(nextSeed + marketLevel * 997 + i * 131)); picked = -1; ui.boxContinue.classList.add('hidden'); renderBoxes(false); ui.boxOverlay.classList.remove('hidden'); ui.boxOverlay.classList.add('flex'); }
function renderBoxes(open){ ui.boxGrid.innerHTML = boxChoices.map((it,i)=>`<button data-box="${i}" class="box-btn rounded-3xl ${open ? (i===picked?'bg-teal-100 ring-4 ring-teal-400':'bg-slate-100 opacity-75') : 'bg-amber-100'} p-3 shadow-lg active:scale-95"><div class="text-5xl">${open?it.icon:'📦'}</div><p class="mt-2 text-xs font-bold ${open?'':'invisible'}">${i===picked?'SEÇTİN':'KAÇIRDIĞIN'}</p><p class="text-[10px] text-slate-600 ${open?'':'invisible'}">${it.name.split('#')[0]}</p><p class="font-display text-sm text-amber-700 ${open?'':'invisible'}">$${it.base}</p></button>`).join(''); document.querySelectorAll('.box-btn').forEach(b=>b.addEventListener('click',()=>chooseBox(Number(b.dataset.box)))); }
function chooseBox(i){ if(picked !== -1) return; initAudio(); picked = i; item = boxChoices[i]; nextSeed += 3; resetLayers(); renderBoxes(true); ui.boxContinue.classList.remove('hidden'); ui.hint.textContent = `Seçtin: ${item.name}`; if(clickSfx) clickSfx.play(); save(); }
function beginCleaning(){ ui.boxOverlay.classList.add('hidden'); ui.boxOverlay.classList.remove('flex'); started = true; setTool('scrape'); ui.hint.textContent = `${dirtNames[item.dirtId]} ürün: ${item.needs.map(t=>({scrape:'kazı',wash:'köpükle/durula',repair:'onar',polish:'cilala'}[t])).join(' + ')}`; updateUi(); }
function sampleClean(){ if(!item) return; const data=dirtCtx.getImageData(0,0,dirtCanvas.width,dirtCanvas.height).data; let visible=0,total=0; for(let i=3;i<data.length;i+=16){ if(data[i]>5) visible++; total++; } cleanRatio = Math.max(0, Math.min(1, 1 - visible/(total*.23))); if(cleanRatio>.94) cleanRatio=1; updateUi(); }
function quality(){ if(!item) return 0; const need=t=>item.needs.includes(t); const clean=cleanRatio, dry=Math.max(0,1-foamRatio*1.25); const washScore=need('wash') ? Math.min(1, clean*.65 + dry*.35) : dry; const repairScore=need('repair') ? repairRatio : 1; const polishScore=need('polish') ? polishRatio : Math.max(.85, polishRatio); return Math.max(0, Math.min(1, clean*.36 + washScore*.14 + repairScore*.25 + polishScore*.20 + dry*.05)); }
function condition(){ return Math.round(quality()*100); }
function quote(){ if(!item) return 0; const foamPenalty = Math.max(0, foamRatio - .12) * .3; return Math.max(5, Math.floor(item.base * Math.max(.08, Math.min(1.25, .22 + quality()*1.03 - foamPenalty)))); }
function setTool(t){ tool = t; if(clickSfx) clickSfx.play(); const tips={scrape:'Kir/pası kazı',wash:'Köpükle ve kiri yumuşat',rinse:'Suyla durula, köpüğü akıt',repair:'Çatlakları ve hasarı onar',polish:'Köpük azaldıktan sonra parlat'}; if(started) ui.hint.textContent=tips[t]||'İşleme devam'; document.querySelectorAll('.tool-btn').forEach(b=>b.classList.toggle('bg-teal-200', b.dataset.tool===tool)); updateUi(); }
function pos(e){ const rect=canvas.getBoundingClientRect(), p=e.touches?e.touches[0]:e; return {x:(p.clientX-rect.left)*(canvas.width/rect.width), y:(p.clientY-rect.top)*(canvas.height/rect.height)}; }
function scrub(e){ if(!started||selling||!dragging||!item) return; e.preventDefault(); const p=pos(e), r=brushRadius(); if(tool==='scrape'||tool==='wash'||tool==='rinse'){ dirtCtx.save(); dirtCtx.globalCompositeOperation='destination-out'; const g=dirtCtx.createRadialGradient(p.x,p.y,r*.12,p.x,p.y,tool==='scrape'?r:r*.9); g.addColorStop(0,'#000'); g.addColorStop(1,'rgba(0,0,0,0)'); dirtCtx.fillStyle=g; dirtCtx.beginPath(); dirtCtx.arc(p.x,p.y,tool==='scrape'?r:r*.9,0,Math.PI*2); dirtCtx.fill(); dirtCtx.restore(); }
  if(tool==='wash'){ foamCtx.save(); foamCtx.globalCompositeOperation = 'source-over'; foamCtx.fillStyle = 'rgba(255,255,255,.72)'; for(let i=0;i<6;i++){ foamCtx.beginPath(); foamCtx.arc(p.x+(Math.random()-.5)*r,p.y+(Math.random()-.5)*r,Math.random()*r*.32+r*.13,0,Math.PI*2); foamCtx.fill(); } foamCtx.restore(); foamRatio = Math.max(0, Math.min(1, foamRatio + .012)); }
  if(tool==='rinse'){ foamCtx.save(); foamCtx.globalCompositeOperation = 'destination-out'; const rg=foamCtx.createRadialGradient(p.x,p.y,r*.15,p.x,p.y,r*1.24); rg.addColorStop(0,'#000'); rg.addColorStop(1,'rgba(0,0,0,0)'); foamCtx.fillStyle=rg; foamCtx.beginPath(); foamCtx.arc(p.x,p.y,r*1.24,0,Math.PI*2); foamCtx.fill(); foamCtx.restore(); foamRatio = Math.max(0, foamRatio - .035 - brushLevel*.003); if(foamRatio < .04) foamRatio = 0; }
  if(tool==='repair') repairRatio = Math.min(1, repairRatio + .009 + brushLevel*.0019);
  if(tool==='polish' && cleanRatio>.35 && foamRatio<.22) polishRatio = Math.min(1, polishRatio + .012 + brushLevel*.0021);
  const colors={scrape:'#a16207',wash:'#f8fafc',rinse:'#38bdf8',repair:'#94a3b8',polish:'#facc15'}; for(let i=0;i<3;i++) particles.push({x:p.x,y:p.y,vx:(Math.random()-.5)*2.2,vy:-Math.random()*2,life:28,color:colors[tool]}); const now=performance.now(); if(now-lastSample>80){ lastSample=now; sampleClean(); } updateUi(); }
function renderShelf(){ ui.shelfList.innerHTML = shelf.length ? shelf.slice(-6).map(s=>`<div class="rounded-xl bg-white/10 p-2 text-center"><p class="text-xl">${s.icon}</p><p class="truncate text-[9px]">${s.name}</p><p class="text-[10px] text-amber-200">$${s.ask}</p></div>`).join('') : '<p class="col-span-3 py-4 text-center text-xs text-slate-400">Raf boş</p>'; }
function processShelf(){ if(!shelf.length) return; const r = Math.random(); shelf = shelf.filter((s,idx)=>{ const chance = Math.min(.65, .16 + s.quality*.42 - idx*.03); if(r + idx*.11 < chance){ money += s.ask; best = Math.max(best, money); floating.push({text:`Raf +$${s.ask}`,x:canvas.width/2,y:canvas.height*.2,life:90}); return false; } return true; }); }
function openMarket(){ if(!started||!item) return; initAudio(); selling=true; sampleClean(); offer = quote(); haggles = 0; ui.dealerLine.textContent = quality() > .9 ? 'Usta işi olmuş, iyi para eder.' : quality() > .55 ? 'Fena değil, biraz pazarlık yapabiliriz.' : 'Eksikleri var ama alıcı bulurum.'; updateMarket(); ui.marketOverlay.classList.remove('hidden'); ui.marketOverlay.classList.add('flex'); renderShelf(); }
function updateMarket(){ ui.marketItem.textContent = `${item.icon} ${item.name}`; ui.marketStats.textContent = `Durum ${condition()}% • Temizlik ${Math.floor(cleanRatio*100)}% • Köpük ${Math.floor(foamRatio*100)}%`; ui.marketOffer.textContent = `$${offer}`; }
function haggle(){ if(haggles>=2){ ui.dealerLine.textContent='Daha fazla çıkamam, karar senin.'; return; } haggles++; const ok = Math.random() < (.72 - haggles*.18 + quality()*.18); if(ok){ offer = Math.floor(offer * (1.08 + Math.random()*.12)); ui.dealerLine.textContent='Hmm... tamam, teklifimi yükseltiyorum.'; } else { offer = Math.max(5, Math.floor(offer * .92)); ui.dealerLine.textContent='Çok istedin, biraz kırarım.'; } updateMarket(); if(upgradeSfx) upgradeSfx.play(); }
function finishSale(earned, shelfed=false){ if(!shelfed){ money += earned; best=Math.max(best,money); ui.earnedText.textContent=`+$${earned}`; ui.completeOverlay.classList.remove('hidden'); ui.completeOverlay.classList.add('flex'); if(sellSfx) sellSfx.play(); for(let i=0;i<90;i++) particles.push({x:canvas.width/2,y:canvas.height/2,vx:(Math.random()-.5)*8,vy:(Math.random()-.5)*8,life:70,color:['#facc15','#2dd4bf','#fff'][i%3]}); } ui.marketOverlay.classList.add('hidden'); ui.marketOverlay.classList.remove('flex'); save(); updateUi(); setTimeout(()=>{ ui.completeOverlay.classList.add('hidden'); generateBoxes(); }, shelfed?400:1400); }
function acceptSale(){ finishSale(offer,false); }
function shelfItem(){ shelf.push({ name:item.name.split('#')[0], icon:item.icon, ask:Math.floor(offer*1.18), quality:quality() }); shelf = shelf.slice(-6); ui.dealerLine.textContent='Rafa koydum. Belki müşteri gelir, belki günlerce bekler.'; save(); renderShelf(); finishSale(0,true); }
function buySpeed(){ initAudio(); const c=speedCost(); if(money<c) return; money-=c; brushLevel++; if(upgradeSfx) upgradeSfx.play(); floating.push({text:'Alet +',x:canvas.width*.5,y:canvas.height*.18,life:55}); save(); updateUi(); }
function buyMarket(){ initAudio(); const c=marketCost(); if(money<c) return; money-=c; marketLevel++; if(upgradeSfx) upgradeSfx.play(); save(); generateBoxes(); updateUi(); }
function updateUi(){ ui.money.textContent=`$${money}`; ui.best.textContent=`Rekor $${best}`; if(!item){ ui.objectName.textContent='Kutu seç'; ui.value.textContent='$0'; ui.sellQuote.textContent='$0'; return; } const q=quote(); ui.objectName.textContent=item.name; ui.value.textContent=`$${q}`; ui.sellQuote.textContent=`$${q}`; ui.condition.textContent=`${condition()}%`; ui.mClean.textContent=`Kir ${Math.floor(cleanRatio*100)}%`; ui.mFoam.textContent=`Köpük ${Math.floor(foamRatio*100)}%`; ui.mRepair.textContent=`Sağlam ${Math.floor(repairRatio*100)}%`; ui.mPolish.textContent=`Cila ${Math.floor(polishRatio*100)}%`; ui.speedCost.textContent=`$${speedCost()}`; ui.unlockCost.textContent=`$${marketCost()}`; ui.speedBtn.disabled=money<speedCost(); ui.unlockBtn.disabled=money<marketCost(); }
function render(){ ctx.clearRect(0,0,canvas.width,canvas.height); const bg=ctx.createLinearGradient(0,0,0,canvas.height); bg.addColorStop(0,'#f8fafc'); bg.addColorStop(1,'#ecfdf5'); ctx.fillStyle=bg; ctx.fillRect(0,0,canvas.width,canvas.height); ctx.fillStyle='rgba(15,118,110,.08)'; ctx.beginPath(); ctx.arc(canvas.width*.5,canvas.height*.58,canvas.width*.34,0,Math.PI*2); ctx.fill(); if(item){ drawSilhouette(ctx,false); if(polishRatio>0){ ctx.globalCompositeOperation='screen'; ctx.globalAlpha=polishRatio*.65; ctx.fillStyle='#fde68a'; ctx.beginPath(); ctx.ellipse(canvas.width*.43,canvas.height*.45,canvas.width*.06,canvas.height*.26,.25,0,Math.PI*2); ctx.fill(); ctx.globalAlpha=1; ctx.globalCompositeOperation='source-over'; } drawDamage(ctx); ctx.drawImage(dirtCanvas,0,0); ctx.drawImage(foamCanvas,0,0); } else { ctx.font=`${90*(canvas.width/400)}px sans-serif`; ctx.textAlign='center'; ctx.fillText('📦',canvas.width/2,canvas.height/2); } particles=particles.filter(p=>p.life-->0); for(const p of particles){p.x+=p.vx;p.y+=p.vy;p.vy+=.045;ctx.globalAlpha=Math.max(0,p.life/70);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,Math.max(1.5,p.life/18),0,Math.PI*2);ctx.fill();} floating=floating.filter(f=>f.life-->0); for(const f of floating){f.y-=.9;ctx.globalAlpha=Math.max(0,f.life/80);ctx.font=`${30*(canvas.width/400)}px BungeeLocal, sans-serif`;ctx.textAlign='center';ctx.lineWidth=5;ctx.strokeStyle='#fff';ctx.fillStyle='#0f766e';ctx.strokeText(f.text,f.x,f.y);ctx.fillText(f.text,f.x,f.y);} ctx.globalAlpha=1; requestAnimationFrame(render); }
function startGame(){ initAudio(); if(clickSfx) clickSfx.play(); ui.startOverlay.style.display='none'; processShelf(); generateBoxes(); updateUi(); }
canvas.addEventListener('pointerdown', e=>{initAudio(); dragging=true; canvas.setPointerCapture(e.pointerId); scrub(e);});
canvas.addEventListener('pointermove', scrub); canvas.addEventListener('pointerup',()=>{dragging=false;sampleClean();}); canvas.addEventListener('pointercancel',()=>dragging=false);
document.querySelectorAll('.tool-btn').forEach(b=>b.addEventListener('click',()=>setTool(b.dataset.tool)));
ui.startBtn.addEventListener('click', startGame); ui.boxContinue.addEventListener('click', beginCleaning); ui.sellBtn.addEventListener('click', openMarket); ui.haggleBtn.addEventListener('click', haggle); ui.acceptBtn.addEventListener('click', acceptSale); ui.shelfBtn.addEventListener('click', shelfItem); ui.speedBtn.addEventListener('click', buySpeed); ui.unlockBtn.addEventListener('click', buyMarket); window.addEventListener('resize', fitCanvas); window.addEventListener('pointerdown', initAudio, {once:true});
fitCanvas(); updateUi(); render();
